### ISSUE TITLE
YAML merge key parsing not correct under lists/array environment

### ISSUE THREAD

**Issue by QiayuanLiao** [xqms/rosmon#150]
Hello, I found that the YAML merge key is working well under the struct environment but not correct under the lists/array environment.
###  YAML code:
```
  defaults: &defaults
    A: 1
    B: 2
  struct:
    <<: *defaults
    A: 23
    C: 99
  array:
    - <<: *defaults
      A: 23
      C: 99
```
### roslaunch outupt:
```
array:
- A: 23
  B: 2
  C: 99
defaults:
  A: 1
  B: 2
struct:
  A: 23
  B: 2
  C: 99

```
### mon launch output:
```
array:
- '<<':
    A: 1
    B: 2
  A: 23
  C: 99
defaults:
  A: 1
  B: 2
struct:
  A: 23
  B: 2
  C: 99
```
### Difference:
Note the  causing by the lists/array environment
```
- '<<':
    A: 1
    B: 2
```
